          name:                   vsongbook  # the name of the snap
          # version:              2.5.5  # the version of the snap
          version:                master
          version-script:         printf "`cat currentrelease | head -n 1 `-`git rev-list master --count`-` git -C . rev-parse --short HEAD`"

          summary:                DB Browser for SQLite  # 79 char long summary
          description:            |
            vSongBook (Virtual Songbook) is a high quality, visual, open source tool to give users access to song lyrics of major worship and praise songbooks used in christian gatherings be it in church, weddings, funerals or anywhere where one feels like singing.
            * Browse, edit, add, and delete songs
            * Search songs realtime
            * Adjust font types and sizes among other display preferences
            * View songs in presentation mode for use over projector.
          confinement:            strict  # use "strict" to enforce system access only via declared interfaces

          grade:                  devel
          icon:                   images/vSongBook.svg
          type:                   app

          apps:
            sqlitebrowser:
              command:            desktop-launch $SNAP/bin/vsongbook
              desktop:            share/applications/vsongbook.desktop
              environment:
                TMPDIR:           $XDG_RUNTIME_DIR
              plugs:
                # - browser-support
                - desktop
                - gsettings
                - home
                # - network
                # - opengl
                - unity7
                - wayland
                - x11
                - removable-media
                # - ssh-keys

          build-packages:
              - build-essential
              - g++
              - qtbase5-dev
              - qttools5-dev
              - qttools5-dev-tools
              - libsqlite3-dev
              - cmake
              - libsqlcipher-dev
              - libqcustomplot-dev
              # - libx11-xcb1
              # - libx11-xcb-dev
              # - libxcb-xkb-dev
              - git
          parts:
              # wrappers:
              #     plugin:         dump
              #     source:         snap/
              sqlitebrowser:
                  # source-type:  git
                  plugin:         cmake
                  configflags:    ["-DUSE_QT5=True", "-Dsqlcipher=1", "-Wno-dev","-DSQLITE_ENABLE_JSON1=1"]
                  source:         .
              desktop-qt5:
                build-packages:
                - qtbase5-dev
                - dpkg-dev
                - libgtk-3-dev
                make-parameters:
                - FLAVOR=qt5
                plugin:           make
                source:           https://github.com/ubuntu/snapcraft-desktop-helpers.git
                source-subdir:    qt
                stage-packages:
                - libxkbcommon0
                # - qt5-gtk-platformtheme
                - ttf-ubuntu-font-family
                - dmz-cursor-theme
                - light-themes
                - adwaita-icon-theme
                - gnome-themes-standard
                - shared-mime-info
                - libgtk-3-0
                - libqt5gui5
                - libgdk-pixbuf2.0-0
                - libqt5svg5
                - appmenu-qt5
                - libglib2.0-bin
                - libgtk-3-bin
                - unity-gtk3-module
                - libappindicator3-1
                - locales-all
                - xdg-user-dirs
                - ibus-gtk3
                - libibus-1.0-5
              dump:
                  plugin:         dump
                  after:
                  - desktop-qt5
                  - vsongbook
                  stage-packages:
                  # - qtbase5-dev
                  # - libqt5gui5
                  # - libqt4gui4
                  # - libxkbcommon0
                  # - libxkbfile1
                  # - gtk2-engines
                  - libc6
                  # - gtk2-engines-oxygen
                  # - gtk3-engines-breeze
                  - libgcc1
                  # - libqcustomplot1.3
                  # - libqt5network5
                  # - libqt5scintilla2-12v5
                  - libsqlite3-0
                  - libstdc++6
                  - libsqlcipher-dev
                  - libatk-adaptor
                  - libgail-common
                  - libgail-3-0
                  - libgail-3-dev
                  - libgail-dev
                  # - qt5-gtk-platformtheme
                  filesets:
                      wanted:
                      - bin/*
                      - share/*
                      - usr/lib/*.*
                      - usr/lib/*-linux-gnu*/libsqlcipher.so.0*
                      - usr/lib/*-linux-gnu*/libdb*
                      - usr/lib/*-linux-gnu*/libz.so*
                      - usr/lib/*-linux-gnu*/libatk*
                      - usr/lib/*-linux-gnu*/libgail*
                      - usr/lib/*-linux-gnu*/gtk-2.0/modules/*
                      - etc/X11/Xsession.d/90atk-adaptor
                      - usr/lib/gnome-settings-daemon-3.0/gtk-modules/at-spi2-atk.desktop
                      - usr/lib/unity-settings-daemon-1.0/gtk-modules/at-spi2-atk.desktop
                  prime:
                  - $wanted

